name: Update patterns.json

on:
  push:
    paths:
      - "patterns/**.pdf"
      - ".github/workflows/update-patterns-json.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate patterns.json
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const dir = 'patterns';
          const files = fs.readdirSync(dir).filter(f => f.toLowerCase().endsWith('.pdf'));
          const data = files.map(f => ({
            // filename without extension will be the display name
            name: path.basename(f, '.pdf'),
            file: path.join(dir, f).replace(/\\/g, '/')
          }));
          fs.writeFileSync('patterns.json', JSON.stringify(data, null, 2));
          "

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add patterns.json
          git commit -m 'Update patterns.json' || echo 'No changes to commit'
          git push
