name: Update patterns.json

permissions:
  contents: write  # this gives write permission to the default GITHUB_TOKEN

on:
  push:
    paths:
      - "patterns/**.pdf"
      - ".github/workflows/update-patterns-json.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate patterns.json
        run: |
          node -e "
          const fs = require('fs');
          const dir = 'patterns';
          const files = fs.readdirSync(dir)
            .filter(f => f.toLowerCase().endsWith('.pdf'))
            .map(f => \`patterns/\${f}\`);
          fs.writeFileSync('patterns.json', JSON.stringify(files, null, 2));
          "

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add patterns.json
          git diff --cached --quiet || git commit -m 'Update patterns.json'
          git push origin HEAD:main
